x-odoo-build: &odoo14-build
  context: ./14.0
  dockerfile: Dockerfile

x-odoo-build: &odoo13-build
  context: ./13.0
  dockerfile: Dockerfile


version: "3.7"
services:

  nginx:
    environment:
    - NGINX_DOCKER_PORT=8080
    env_file: .env
    image: nginx:latest
    container_name: nginx_odoo
    restart: unless-stopped
    depends_on:
      - odoo14
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./nginx/conf/odoo:/etc/nginx/conf.d/default.conf
    networks:
      - net1
      
  db:
    env_file: .env
    image: postgres:12
    container_name: db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5444:5432"
    networks:
      - net1

  odoo13:
    container_name: odoo13_app
    env_file: .env
    environment: 
      - PGDATABASE=odoo13
    build: *odoo13-build
    image: odoogap/odoo13
    restart: unless-stopped
    volumes:
      - odoo13_home:/opt/odoo/
    depends_on:
      - db
    networks:
      - net1

  odoo14:
    container_name: odoo14_app
    env_file: .env
    environment: 
      - PGDATABASE=odoo14
    build: *odoo14-build
    image: odoogap/odoo14
    restart: unless-stopped
    volumes:
      - odoo14_home:/opt/odoo/
    depends_on:
      - db
    networks:
      - net1

volumes:
  db_home:
    external: false
  odoo13_home:
    external: false
  odoo14_home:
    external: false

networks:
  net1: 
    name: net1
