version: "3.7"

x-odoo-build: &odoo-build
  context: ./14.0
  dockerfile: Dockerfile


services:

  nginx:
    env_file: .env
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - odoo14
    ports:
      - 8080:80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - web-root:/var/www/html
    environment:
      - NGINX_HOST=localhost:8080
    networks:
      - net1
      
  db:
    env_file: .env
    image: postgres:12
    container_name: db
    restart: unless-stopped
    ports:
      - "127.0.0.1:5444:5432"
    networks:
      - net1
    volumes:
      - db_home:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=odoo14

  odoo14:
    container_name: odoo_replica1
    env_file: .env
    build: *odoo-build
    image: odoogap/odoo14
    restart: unless-stopped
    volumes:
      - odoo14_home:/var/lib/odoo
      - ~/git/oe/14.0/:/mnt/oe
    depends_on:
      - db
    networks:
      - net1

  odoo14_2:
    container_name: odoo_replica2
    env_file: .env
    build: *odoo-build
    image: odoogap/odoo14
    restart: unless-stopped
    volumes:
      - odoo14_home:/var/lib/odoo
      - ~/git/oe/14.0/:/mnt/oe
    depends_on:
      - db
    networks:
      - net1

volumes:
  db_home:
    external: false
  odoo14_home:
    external: false
  web-root:
    external: false

networks:
  net1: 
    name: net1
